name: Testing

on: [push, pull_request]

jobs:
  laravel6:
    name: Laravel 6.x
    uses: ./.github/workflows/phpunit2-laravel.yml
    with:
      laravel: 6.*
      php: '["8.1", "8.2", "8.3", "8.4", "8.5"]'
  laravel7:
    name: Laravel 7.x
    uses: ./.github/workflows/phpunit2-laravel.yml
    with:
      laravel: 7.*
      php: '["8.1", "8.2", "8.3", "8.4", "8.5"]'
  laravel8:
    name: Laravel 8.x
    uses: ./.github/workflows/phpunit2-laravel.yml
    with:
      laravel: 8.*
      php: '["8.1", "8.2", "8.3", "8.4", "8.5"]'
