name: PHPUnit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        laravel: [6.*, 7.*, 8.*, 9.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 6.*
            doctrine: ^2.6
            testbench: 4.*
          - laravel: 7.*
            doctrine: ^2.6
            testbench: 5.*
          - laravel: 8.*
            doctrine: 3.*
            testbench: 6.*
          - laravel: 9.*
            doctrine: 3.*
            testbench: 7.*
        exclude:
          - php: 8.1
            laravel: 6.*
          - php: 8.1
            laravel: 7.*
          - php: 8.2
            laravel: 6.*
          - php: 8.2
            laravel: 7.*
          - php: 8.2
            laravel: 8.*
            stability: prefer-lowest
          - php: 8.2
            laravel: 9.*
            stability: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, pdo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "doctrine/dbal:${{ matrix.doctrine }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_HOST: localhost
          DB_DATABASE: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
